spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/