spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/